backend:
  name: github
  repo: gaogao-asia/gaogao-techblog

media_folder: static/media
public_folder: /media
collections:
  - name: posts
    label: Posts
    label_singular: 'Post'
    folder: content/posts
    slug: "{{year}}-{{month}}-{{day}}--{{title}}"
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: cover, label: 'Cover Image', widget: 'image' }
      - { name: author, label: Author }
      - { name: body, label: Body, widget: markdown }