backend:
  name: github
  repo: gaogao-asia/gaogao-techblog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: cover, label: Cover }
      - { name: author, label: Author }
      - { name: body, label: Body, widget: markdown }